baseURL = "https://rejewski-seclabs.org/"
languageCode = "en-us"
title = "Hugo Hero Theme"
theme = "hero"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "logo.png"
    desktop_height = "80px"
    desktop_width = "250px"
    alt = "Rejewski SecLabs"

  [params.homepage_meta_tags]
    meta_description = "Centro de Investigacion, Innovacion y Emprendimiento"
    meta_og_title = "Rejewski Security Labs"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Centro de Investigación, Innovación y Emprendimiento"
    meta_twitter_card = "Centro de Investigacion, Innovacion y Emprendimiento"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Nosotros"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
