baseURL: https://rejewski-seclabs.org/
languageCode: en-us
title: Rejewski Security Labs
theme: default
defaultContentLanguage: es
languages:
  es:
    contentDir: content/es
    params:
      subtext: Centro de Investigación, Innovación y Emprendimiento
      about: Conocenos
      description: Somos un equipo comprometido al desarrollo de iniciativas en tecnologías de la información y las comunicaciones enfocadas en ciberseguridad. Con la colaboración de universidades u otras instituciones académicas, nos esforzamos en establecer avances y contribuciones científicas únicas a través de la ejecución de proyectos de investigación en ciberseguridad.
      contact: Contactanos
      text404: Error 404 - Page Not Found
    menu:
      main:
        - identifier: home
          name: Home
          url: /es
          weight: 1
        - identifier: about
          name: Conocenos
          url: /es#about
          weight: 2
        - identifier: mandelbrot
          name: Programa Mandelbrot
          url: /es/mandelbrot
          weight: 3
        - identifier: contact
          name: Contactanos
          url: /es#contact
          weight: 4
        - identifier: en
          name: English Version
          url: https://rejewski-seclabs.org/en
          weight: 5
  en:
    contentDir: content/en
    params:
      subtext: A Hub for Research, Innovation, and Entrepreneurship
      about: About Us
      description: We are committed to developing research initiatives on cybersecurity-focused technology for information and communication systems. By collaborating with universities and other academic institutions, we strive to establish in-depth and unique initiatives that contribute to scientific advancement.
      contact: Contact Us
      text404: Error 404 - Page Not Found
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: about
          name: About
          url: /#about
          weight: 2
        - identifier: mandelbrot
          name: Mandelbrot Program
          url: /mandelbrot
          weight: 3
        - identifier: contact
          name: Contact
          url: /#contact
          weight: 4
        - identifier: es
          name: Spanish Version
          url: https://rejewski-seclabs.org/es
          weight: 5
