baseURL: https://rejewski-seclabs.org/
languageCode: en-us
title: Rejewski Security Labs
theme: default
defaultContentLanguage: en
languages:
  es:
    params:
      subtext: Centro de Investigación, Innovación y Emprendimiento
      about: Conocenos
      description: Somos un equipo comprometido al desarrollo de iniciativas en ciberseguridad enfocadas a tecnologías de la información y las comunicaciones. Con la colaboración de universidad u otras instituciones académicas, nos esforzamos en establecer avanzadas y únicas contribuciones científicas.
      contact: Contactanos
  en:
    params:
      subtext: A Hub for Research, Innovation, and Entrepreneurship
      about: About Us
      description: We are committed to developing research initiatives on cybersecurity-focused technology for information and communication systems. By collaborating with universities and other academic institutions, we strive to establish in-depth and unique initiatives that contribute to scientific advancement.
      contact: Contact Us
